var _URLS = {
  "ap-beijing": "https://cos.ap-beijing.myqcloud.com",
  "ap-chengdu": "https://cos.ap-chengdu.myqcloud.com",
  "ap-chongqing": "https://cos.ap-chongqing.myqcloud.com",
  "ap-guangzhou": "https://cos.ap-guangzhou.myqcloud.com",
  "ap-nanjing": "https://cos.ap-nanjing.myqcloud.com",
  "ap-shanghai": "https://cos.ap-shanghai.myqcloud.com",
  "ap-beijing-fsi": "https://cos.ap-beijing-fsi.myqcloud.com",
  "ap-shanghai-fsi": "https://cos.ap-shanghai-fsi.myqcloud.com",
  "ap-shenzhen-fsi": "https://cos.ap-shenzhen-fsi.myqcloud.com",
  "ap-hongkong": "https://cos.ap-hongkong.myqcloud.com",
  "ap-bangkok": "https://cos.ap-bangkok.myqcloud.com",
  "ap-jakarta": "https://cos.ap-jakarta.myqcloud.com",
  "ap-seoul": "https://cos.ap-seoul.myqcloud.com",
  "ap-singapore": "https://cos.ap-singapore.myqcloud.com",
  "ap-tokyo": "https://cos.ap-tokyo.myqcloud.com",
  "eu-frankfurt": "https://cos.eu-frankfurt.myqcloud.com",
  "na-ashburn": "https://cos.na-ashburn.myqcloud.com",
  "na-siliconvalley": "https://cos.na-siliconvalley.myqcloud.com",
  "sa-saopaulo": "https://cos.sa-saopaulo.myqcloud.com",
};
