let _DESCS = {
  'ap-beijing': '北京 Beijing',
  'ap-chengdu': '成都 Chengdu',
  'ap-chongqing': '重庆 Chongqing',
  'ap-guangzhou': '广州 Guangzhou',
  'ap-nanjing': '南京 Nanjing',
  'ap-shanghai': '上海 Shanghai',
  'ap-beijing-fsi': '北京金融 Beijing FSI',
  'ap-shanghai-fsi': '上海金融 Shanghai FSI',
  'ap-shenzhen-fsi': '深圳金融 Shenzhen FSI',
  'ap-hongkong': '香港 Hongkong',
  'ap-bangkok': '曼谷 Bangkok',
  'ap-jakarta': '雅加达 Jakarta',
  'ap-seoul': '首尔 Seoul',
  'ap-singapore': '新加坡 Singapore',
  'ap-tokyo': '东京 Tokyo',
  'eu-frankfurt': '法兰克福 Frankfurt',
  'na-ashburn': '美东 阿什本 Ashburn',
  'na-siliconvalley': '美西 硅谷 Silicon Valley',
  'sa-saopaulo': '巴西 圣保罗 Sao Paulo',
};
