var _URLS = {
  "syd-au": "https://syd-au-ping.vultr.com",
  "mel-au": "https://mel-au-ping.vultr.com",
  "hnd-jp": "https://hnd-jp-ping.vultr.com",
  "sel-kor": "https://sel-kor-ping.vultr.com",
  "sgp": "https://sgp-ping.vultr.com",
  "lax-ca-us": "https://lax-ca-us-ping.vultr.com",
  "sjo-ca-us": "https://sjo-ca-us-ping.vultr.com",
  "fl-us": "https://fl-us-ping.vultr.com",
  "ga-us": "https://ga-us-ping.vultr.com",
  "hon-hi-us": "https://hon-hi-us-ping.vultr.com",
  "il-us": "https://il-us-ping.vultr.com",
  "nj-us": "https://nj-us-ping.vultr.com",
  "tx-us": "https://tx-us-ping.vultr.com",
  "wa-us": "https://wa-us-ping.vultr.com",
  "tor-ca": "https://tor-ca-ping.vultr.com",
  "mex-mx": "https://mex-mx-ping.vultr.com",
  "sao-br": "https://sao-br-ping.vultr.com",
  "fra-de": "https://fra-de-ping.vultr.com",
  "mad-es": "https://mad-es-ping.vultr.com",
  "par-fr": "https://par-fr-ping.vultr.com",
  "lon-gb": "https://lon-gb-ping.vultr.com",
  "ams-nl": "https://ams-nl-ping.vultr.com",
  "waw-pl": "https://waw-pl-ping.vultr.com",
  "sto-se": "https://sto-se-ping.vultr.com",
};
