let _DESCS = {
  'syd-au': '悉尼 Sydney',
  'mel-au': '墨尔本 Melbourne',
  'hnd-jp': '东京 Tokyo',
  'sel-kor': '首尔 Seoul',
  'sgp': '新加坡 Singapore',
  'lax-ca-us': '洛杉矶 Los Angeles',
  'sjo-ca-us': '硅谷 Silicon Valley',
  'fl-us': '迈阿密 Miami',
  'ga-us': '亚特兰大 Atlanta',
  'hon-hi-us': '檀香山 Honolulu',
  'il-us': '芝加哥 Illinois',
  'nj-us': '纽约 New Jersey',
  'tx-us': '达拉斯 Dallas',
  'wa-us': '西雅图 Seattle',
  'tor-ca': '多伦多 Toronto',
  'mex-mx': '墨西哥城 Mexico City',
  'sao-br': '圣保罗 Sao Paulo',
  'fra-de': '法兰克福 Frankfurt',
  'mad-es': '马德里 Madrid',
  'par-fr': '巴黎 Paris',
  'lon-gb': '伦敦 London',
  'ams-nl': '阿姆斯特丹 Amsterdam',
  'waw-pl': '华沙 Warsaw',
  'sto-se': '斯德哥尔摩 Stockholm',
};
