var _URLS = {
  "aliyun-cn-qingdao": "https://oss-cn-qingdao.aliyuncs.com",
  "aliyun-cn-beijing": "https://oss-cn-beijing.aliyuncs.com",
  "aliyun-cn-zhangjiakou": "https://oss-cn-zhangjiakou.aliyuncs.com",
  "aliyun-cn-huhehaote": "https://oss-cn-huhehaote.aliyuncs.com",
  "aliyun-cn-chengdu": "https://oss-cn-chengdu.aliyuncs.com",
  "aliyun-cn-guangzhou": "https://oss-cn-guangzhou.aliyuncs.com",
  "aliyun-cn-heyuan": "https://oss-cn-heyuan.aliyuncs.com",
  "aliyun-cn-hangzhou": "https://oss-cn-hangzhou.aliyuncs.com",
  "aliyun-cn-shanghai": "https://oss-cn-shanghai.aliyuncs.com",
  "aliyun-cn-shenzhen": "https://oss-cn-shenzhen.aliyuncs.com",
  "aliyun-cn-wulanchabu": "https://oss-cn-wulanchabu.aliyuncs.com",
  "aliyun-cn-hongkong": "https://oss-cn-hongkong.aliyuncs.com",
  "aliyun-ap-southeast-1": "https://oss-ap-southeast-1.aliyuncs.com",
  "aliyun-ap-southeast-2": "https://oss-ap-southeast-2.aliyuncs.com",
  "aliyun-ap-southeast-3": "https://oss-ap-southeast-3.aliyuncs.com",
  "aliyun-ap-southeast-5": "https://oss-ap-southeast-5.aliyuncs.com",
  "aliyun-ap-southeast-6": "https://oss-ap-southeast-6.aliyuncs.com",
  "aliyun-ap-southeast-7": "https://oss-ap-southeast-7.aliyuncs.com",
  "aliyun-ap-northeast-1": "https://oss-ap-northeast-1.aliyuncs.com",
  "aliyun-ap-northeast-2": "https://oss-ap-northeast-2.aliyuncs.com",
  "aliyun-us-west-1": "https://oss-us-west-1.aliyuncs.com",
  "aliyun-us-east-1": "https://oss-us-east-1.aliyuncs.com",
  "aliyun-eu-central-1": "https://oss-eu-central-1.aliyuncs.com",
  "aliyun-eu-west-1": "https://oss-eu-west-1.aliyuncs.com",
  "aliyun-me-east-1": "https://oss-me-east-1.aliyuncs.com",
  "aliyun-ap-south-1": "https://oss-ap-south-1.aliyuncs.com",
};
