let _DESCS = {
  'aliyun-cn-qingdao': '青岛 华北1',
  'aliyun-cn-beijing': '北京 华北2',
  'aliyun-cn-zhangjiakou': '张家口 华北3',
  'aliyun-cn-huhehaote': '呼和浩特 华北5',
  'aliyun-cn-chengdu': '成都 西南1',
  'aliyun-cn-guangzhou': '广州 华南2',
  'aliyun-cn-heyuan': '河源 华南3',
  'aliyun-cn-hangzhou': '杭州 华东1',
  'aliyun-cn-shanghai': '上海 华东2',
  'aliyun-cn-shenzhen': '深圳 华南1',
  'aliyun-cn-wulanchabu': '乌兰察布 华北6',
  'aliyun-cn-hongkong': '中国香港',
  'aliyun-ap-southeast-1': '新加坡 亚太东南1',
  'aliyun-ap-southeast-2': '悉尼 亚太东南2',
  'aliyun-ap-southeast-3': '吉隆坡 亚太东南3',
  'aliyun-ap-southeast-5': '雅加达 亚太东南5',
  'aliyun-ap-southeast-6': '马尼拉 亚太东南6',
  'aliyun-ap-southeast-7': '曼谷 亚太东南7',
  'aliyun-ap-northeast-1': '东京 亚太东北1',
  'aliyun-ap-northeast-2': '首尔 亚太东北2',
  'aliyun-us-west-1': '硅谷 美国西部1',
  'aliyun-us-east-1': '弗吉尼亚 美国东部1',
  'aliyun-eu-central-1': '法兰克福 欧洲中部1',
  'aliyun-eu-west-1': '伦敦 英国',
  'aliyun-me-east-1': '迪拜 中东东部1',
  'aliyun-ap-south-1': '孟买 亚太南部1',
};
